# Stage 1: Base
ARG NODE_VERSION=20.12.2
FROM node:${NODE_VERSION}-alpine AS base
ENV NODE_ENV=development
RUN apk add --no-cache libc6-compat bash git

# Stage 2: Dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
npm install

# Stage 3: Runtime
FROM base AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]