services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: runner
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped