services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - ./frontend/node_modules/
        - action: rebuild
          path: ./frontend/package.json