# Stage 1: Base
ARG NODE_VERSION=20.12.2
FROM node:${NODE_VERSION}-alpine AS base
ENV NODE_ENV=production
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto \
    bash \
    git \
    curl \
    udev \
    alsa-lib \
    libx11 \
    libxcomposite \
    libxdamage \
    libxrandr \
    libxrender \
    libxext \
    libxi \
    libxtst \
    libc6-compat \
    pango \
    cairo

# Stage 2: Build
FROM base AS build

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm prisma generate
RUN pnpm run build

# Stage 3: Runtime
FROM base AS prod

COPY --from=build /app/pnpm-lock.yaml .
COPY --from=build /app/package.json .

RUN pnpm install --frozen-lockfile

COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

CMD ["sh", "-c", "pnpm prisma migrate deploy && node dist/main.js"]