ARG NODE_VERSION=20.12.2
FROM node:${NODE_VERSION}-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto \
    bash \
    git \
    curl \
    udev \
    alsa-lib \
    libx11 \
    libxcomposite \
    libxdamage \
    libxrandr \
    libxrender \
    libxext \
    libxi \
    libxtst \
    libc6-compat \
    pango \
    cairo

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm add -D nodemon
RUN pnpm prisma generate

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

EXPOSE 4200

CMD ["pnpm", "run", "start:dev"]
