export const DOCUMENT_SECTION_NAMES_MAP = {
  resume: [
		"personalDetails",
  	"professionalSummary",
  	"employmentHistory",
		"employmentHistoryItem",
  	"education",
		"educationItem",
  	"links",
		"linkItem",
  	"skills",
		"skillItem",
  	"languages",
		"languageItem",
  	"courses",
		"courseItem",
  	"internships",
		"internshipItem",
  	"hobbies",
  	"extraCurricularActivities",
		"extraCurricularActivityItem",
  	"references",
		"referenceItem",
  	"customSection",
		"customSectionItem",
	],
  coverLetter: [
		"personalDetails",
		"employerDetails",
		"letterDetails",
	],
} as const;