export const DOCUMENT_TYPES_MAP = {
  resume: {
    name: "Резюме",
    sectionTemplates: [
      "personalDetails",
      "professionalSummary",
      "employmentHistory",
      "employmentHistoryItem",
      "education",
      "educationItem",
      "links",
      "linkItem",
      "skills",
      "skillItem",
      "languages",
      "languageItem",
      "courses",
      "courseItem",
      "internships",
      "internshipItem",
      "hobbies",
      "extraCurricularActivities",
      "extraCurricularActivityItem",
      "references",
      "referenceItem",
      "customSection",
      "customSectionItem",
    ],
    templates: ["classic", "modern"],
  },
  coverLetter: {
    name: "Сопроводительные письма",
    sectionTemplates: ["personalDetails", "employerDetails", "letterDetails"],
    templates: ["classic", "minimal"],
  },
} as const;
