export const DOCUMENT_CONFIG = {
	resume: {
		name: "Резюме",
		typePlural: "resumes",
		sectionTemplates: [
			"personalDetails",
			"professionalSummary",
			"employmentHistory",
			"employmentHistoryItem",
			"education",
			"educationItem",
			"links",
			"linkItem",
			"skills",
			"skillItem",
			"languages",
			"languageItem",
			"courses",
			"courseItem",
			"internships",
			"internshipItem",
			"hobbies",
			"extraCurricularActivities",
			"extraCurricularActivityItem",
			"references",
			"referenceItem",
			"customSection",
			"customSectionItem",
		],
		templates: ["classic", "modern"],
	},
	coverLetter: {
		name: "Сопроводительные письма",
		typePlural: "coverLetters",
		sectionTemplates: ["personalDetails", "employerDetails", "letterDetails"],
		templates: ["classic", "minimal"],
	},
} as const;
